exec-once = $SwwwRandom  # random wallpaper switcher every 30 minutes
exec-once = qs # quickshell AGS Desktop Overview alternative
exec-once = sh -c 'sleep 1 && hyprctl dispatch workspace 2'
exec-once = [workspace 1] kitty
exec-once = [workspace 2] code
exec-once = [workspace 2] firedragon --restore
exec-once = [workspace 2] kitty
exec-once = [workspace special spotify] sh -c 'sleep 2 && spotify'
