---
- name: Example from an Ansible Playbook
  hosts: all
  gather_facts: true
  vars:
    remote_regular_user: "root"
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:
        data: "Hello, World!"

    - name: RHEL install
      ansible.builtin.include_tasks: install-rhel.yml
      when: ansible_facts['os_family'] == "RedHat"

    - name: Debian install
      ansible.builtin.include_tasks: install-debian.yml
      when: ansible_facts['os_family'] == "Debian"

    - name: Universal install
      ansible.builtin.include_tasks: install-linux.yml

    - name: Install  packages
      ansible.builtin.package:
        name:
          - nano
          - htop
          - git
          - python3
          - zsh
          - git
          - htop
          - gh
          - helm
          - zsh
          - fzf
          - tmux
          - autoconf
          - openssl
          - openssh-server
          - tar
          - unzip
          - nano
          - unar
          - bat
          - jq
          - yq
          - nodejs
          - python3
          - openvpn
          - wget
          - curl
          - nmap
          - k9s
          - kubectl
        state: present
      become: true

    - name: Change shell to zsh
      ansible.builtin.user:
        name: "{{ remote_regular_user }}"
        shell: /usr/bin/zsh

    - name: Ensure fonts directory
      ansible.builtin.file:
        path: "~{{ remote_regular_user }}/.fonts"
        state: directory
        mode: "0755"
        owner: "{{ remote_regular_user }}"

    # - name: Check if Jetbrains Mono exists
    #   ansible.builtin.shell: "ls ~{{ remote_regular_user }}/.fonts/JetBrainsMonoNerd*FontMono*"
    #   register: jetbrains_mono_exists
    #   ignore_errors: true
    #   changed_when: false

    # - name: Download Jetbrains mono
    #   when: jetbrains_mono_exists is failed
    #   ansible.builtin.unarchive:
    #     src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip
    #     dest: "~{{ remote_regular_user }}/.fonts/"
    #     remote_src: true
    #     mode: "0755"
    #     owner: "{{ remote_regular_user }}"
    # - name: Machine setup
    # hosts: localhost
    # become: true
    # connection: local
    # gather_facts: true
